{
    'name': 'Sendgrid Sync',
    'version': '1.0',
    'category': 'Contact',
    'sequence': 1,
    'website': 'www.technians.com',
    'summary': 'Sync Odoo with Sendgrid',
    'description': 'Sendgrid Contact Sync',
    'author': 'Rahul Yadav',
    'depends': ['base', 'contacts', 'crm', 'hr_recruitment'],

    'data': [
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/res_config_settings.xml',
        # 'views/sendgrid_stats.xml',
        'views/contact_custom_fields.xml',
        'views/contacts_fields_link.xml',
        'views/crm_fields_link.xml',
        'views/crm_lead.xml',
        'views/applicant_fields_link.xml',
        'views/hr_applicant.xml',
        'views/automation.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'LGPL-3',
    'external_dependencies': {'python': ['sendgrid']},
    'installable': True,
    'auto_install': False,
}
